FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# T3EXLINEJson

Polls is a simple API allowing consumers to view polls and vote in them.

## a-0 [/a0]

### a-0 [GET]

+ Response 201 (application/json)

        {
          "type": "template",
          "altText": "this is a carousel template",
          "template": {
            "type": "carousel",
            "actions": [],
            "columns": [
              {
                "thumbnailImageUrl": "http://a.ecimg.tw/items/DBACC4A900872CC/000001_1514860183.jpg",
                "title": "【ENAAK】香脆點心麵 (16gx12包) 網路價 $75",
                "text": "◎韓國、團購熱銷商品  ◎香濃可口的雞汁風味  ◎搭配口感酥脆、風味獨特  ◎一吃上癮好滋味 ",
                "actions": [
                  {
                    "type": "uri",
                    "label": "前往購買",
                    "uri": "http://24h.pchome.com.tw/prod/DBACC4-A900872CC"
                  }
                ]
              },
              {
                "thumbnailImageUrl": "http://a.ecimg.tw/items/DBAEANA9008JI3J/000001_1510554342.jpg",
                "title": "【HIRO】薯片-番茄風味 160g 網路價 $58",
                "text": "完美厚度，片片薄脆，番茄風味讓喜愛酸味的朋友無法抗拒，一口接一口",
                "actions": [
                  {
                    "type": "uri",
                    "label": "前往購買",
                    "uri": "http://24h.pchome.com.tw/prod/DBAEAN-A9008JI3J"
                  }
                ]
              },
              {
                "thumbnailImageUrl": "http://a.ecimg.tw/items/DBAEA1A9008AN2D/i010001_1502266662.jpg",
                "title": "【Tiffany】Light輕爽小麥消化餅 250g 網路價 $76",
                "text": "小麥減量，讓不喜歡小麥味道的朋友，也能夠輕易地接受，但卻能獲得同樣的營養價值。  ★小麥精選研磨，香氣迷人  ",
                "actions": [
                  {
                    "type": "uri",
                    "label": "前往購買",
                    "uri": "http://24h.pchome.com.tw/prod/DBAEA1-A9008AN2D?q=/S/DBAEA0"
                  }
                ]
              },
              {
                "thumbnailImageUrl": "https://i.imgur.com/Ap3VX0k.jpg",
                "title": "【空運零食大賞】完整攻略！",
                "text": "點進完整清單，各國零食隨意敗",
                "actions": [
                  {
                    "type": "uri",
                    "label": "零食大賞完整清單",
                    "uri": "https://24h.pchome.com.tw/region/DBAE"
                  }
                ]
              }
            ]
          }
        }
        
## D-0 [/d0]

### D-0 [GET]

+ Response 200 (application/json)

        {
          "type": "imagemap",
          "baseUrl": "https://i.imgur.com/X2Ely9e.jpg",
          "altText": "This is an imagemap",
          "baseSize": {
            "width": 1040,
            "height": 1040
          },
          "actions": [
            {
              "type": "message",
              "area": {
                "x": 0,
                "y": 0,
                "width": 340,
                "height": 1040
              },
              "text": "吃貨最愛"
            },
            {
              "type": "message",
              "area": {
                "x": 693,
                "y": 0,
                "width": 347,
                "height": 1040
              },
              "text": "生活小物"
            },
            {
              "type": "message",
              "area": {
                "x": 340,
                "y": 0,
                "width": 353,
                "height": 1040
              },
              "text": "時尚流行"
            }
          ]
        }
        
## D-1 [/d1]

### D-1 [GET]

+ Response 200 (application/json)

                {
          "type": "template",
          "altText": "this is a carousel template",
          "template": {
            "type": "carousel",
            "actions": [],
            "columns": [
              {
                "thumbnailImageUrl": "https://i.imgur.com/iKR3eNL.jpg",
                "title": "【櫻桃爺爺】棗到幸福禮盒(經典牛軋糖+英式太妃糖+南棗核桃糕) 網路價 $359",
                "text": "．獨家款禮盒  櫻桃爺爺堅持純天然食材  ．甜度適中，不添加人工香料、防腐劑。 ",
                "actions": [
                  {
                    "type": "message",
                    "label": "前往購買",
                    "text": "http://24h.pchome.com.tw/prod/DBAR4V-A9007QKQE?q=/S/DBARA9"
                  }
                ]
              },
              {
                "thumbnailImageUrl": "https://i.imgur.com/HccrLEM.jpg",
                "title": "【Kenji健司】醇。北海道牛奶法蘭酥(63g/6包入) 網路價 $69",
                "text": "★美式賣場知名品牌【Kenji健司】出品，優質、美味、安心  ★業界首創添加北海道牛奶7.3%，真材實料 ",
                "actions": [
                  {
                    "type": "uri",
                    "label": "前往購買",
                    "uri": "https://24h.pchome.com.tw/prod/DBAR5I-A9008P1KO"
                  }
                ]
              },
              {
                "thumbnailImageUrl": "https://i.imgur.com/GJO1HD7.jpg",
                "title": "[喬安牧場] 高梁 酒辣味牛肉乾 180g 網路價 $209",
                "text": "★新鮮100%-嚴選新鮮材料製作  ★衛生100%- 生產嚴格把關  ★創新100%- 口味，營養不斷研發 ",
                "actions": [
                  {
                    "type": "uri",
                    "label": "前往購買",
                    "uri": "http://24h.pchome.com.tw/prod/DBAR5J-A9006040P?q=/S/DBARAD"
                  }
                ]
              }
            ]
          }
        }
        
## D-2 [/d2]

### D-2 [GET]

+ Response 200 (application/json)

        {
          "type": "template",
          "altText": "this is a carousel template",
          "template": {
            "type": "carousel",
            "actions": [],
            "columns": [
              {
                "thumbnailImageUrl": "https://i.imgur.com/AfFMMrD.jpg",
                "title": "《DeBelle美人衣學館》夏裝高腰露肩綁帶鬆緊腰棉麻連身寬褲 網路價 $916",
                "text": "上身超彈性，適合S~XL身形。韓妞優雅復古度假風女神棉麻連身褲，性感露肩一字領，襯出迷人肩線，多了成熟的時髦性感",
                "actions": [
                  {
                    "type": "uri",
                    "label": "前往購買",
                    "uri": "http://24h.pchome.com.tw/prod/DIBAQ5-A90077YJK?q=/A/98678"
                  }
                ]
              },
              {
                "thumbnailImageUrl": "https://i.imgur.com/8Ymsh1L.jpg",
                "title": "【韓國K.W.】名媛穿搭壓摺無袖高腰褲套裝(2色) 網路價 $899",
                "text": "明星首選品牌  中大尺碼獨家活動限量販售  韓妞必備品牌  無論華麗復古、可愛俏皮，小資熟女都適合！ ",
                "actions": [
                  {
                    "type": "uri",
                    "label": "前往購買",
                    "uri": "http://24h.pchome.com.tw/prod/DIBAGI-A90080ZFO"
                  }
                ]
              },
              {
                "thumbnailImageUrl": "https://i.imgur.com/qiDPbvk.jpg",
                "title": "【Fairy Charm】韓風簡約金屬亮片頸鍊 網路價 $289",
                "text": "★日韓連線 流行不斷線★  ★韓劇嚴選熱銷款★  ★簡約有型 街拍熱門款★",
                "actions": [
                  {
                    "type": "uri",
                    "label": "前往購買",
                    "uri": "http://24h.pchome.com.tw/prod/DIAERU-A9007IR9Q"
                  }
                ]
              }
            ]
          }
        }
        
## D-3 [/d3]

### D-3 [GET]

+ Response 200 (application/json)

        {
          "type": "template",
          "altText": "this is a carousel template",
          "template": {
            "type": "carousel",
            "actions": [],
            "columns": [
              {
                "thumbnailImageUrl": "https://i.imgur.com/GgLN2Yn.jpg",
                "title": "[IHERMI]鋼琴鍵抱枕B款/” 44cm “/含枕心/台灣製 網路價 525",
                "text": "★台灣設計師打造  ★高品質印染技術  ★奢華的絲綢布，光亮又柔順 ",
                "actions": [
                  {
                    "type": "uri",
                    "label": "前往購買",
                    "uri": "http://24h.pchome.com.tw/prod/DEAZ1O-A9007MR3L"
                  }
                ]
              },
              {
                "thumbnailImageUrl": "https://i.imgur.com/EQuZqen.jpg",
                "title": "【Life Plus】典雅格紋舒壓萬用靠枕/抱枕 (藍咖格紋) 網路價 $639",
                "text": "◆三角造型，能貼合沙發及床背  ◆可拆式圓柱靠枕，可做護頸枕、腿枕使用  ◆鈕扣式拼裝，可任意調節支撐高度 ",
                "actions": [
                  {
                    "type": "uri",
                    "label": "前往購買",
                    "uri": "http://24h.pchome.com.tw/prod/DEAZ1O-A9008VOGN"
                  }
                ]
              },
              {
                "thumbnailImageUrl": "https://i.imgur.com/Qn2RxRO.jpg",
                "title": "【歐士OSHI】轉杯架 (狗)",
                "text": "❖結合吸水杯墊+杯架+調棒 3種功能❖內含白色馬克杯1個 。❖生日/開學/送禮/交換禮物 ",
                "actions": [
                  {
                    "type": "message",
                    "label": "前往購買",
                    "text": "http://24h.pchome.com.tw/prod/DEAZLH-A90080ZFD"
                  }
                ]
              }
            ]
          }
        }