FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# T3EXLINEJson

Polls is a simple API allowing consumers to view polls and vote in them.

## a-0 [/a0]

### a-0 [GET]

+ Response 201 (application/json)

        {
          "type": "template",
          "altText": "this is a carousel template",
          "template": {
            "type": "carousel",
            "actions": [],
            "columns": [
              {
                "thumbnailImageUrl": "https://i.imgur.com/MO1vDu8.jpg",
                "title": "【ENAAK】香脆點心麵 (16gx12包) 網路價 $75",
                "text": "◎韓國、團購熱銷商品  ◎香濃可口的雞汁風味  ◎搭配口感酥脆、風味獨特  ◎一吃上癮好滋味  ◎大人、小孩都愛吃的零嘴",
                "actions": [
                  {
                    "type": "uri",
                    "label": "前往購買",
                    "uri": "http://24h.pchome.com.tw/prod/DBACC4-A900872CC"
                  }
                ]
              },
              {
                "thumbnailImageUrl": "https://i.imgur.com/IsKBqmu.jpg",
                "title": "【HIRO】薯片-番茄風味 160g 網路價 $58",
                "text": "完美厚度，片片薄脆，番茄風味讓喜愛酸味的朋友無法抗拒，一口接一口",
                "actions": [
                  {
                    "type": "uri",
                    "label": "前往購買",
                    "uri": "http://24h.pchome.com.tw/prod/DBAEAN-A9008JI3J"
                  }
                ]
              },
              {
                "thumbnailImageUrl": "https://i.imgur.com/9ZAKKLt.jpg",
                "title": "【Tiffany】Light輕爽小麥消化餅 250g 網路價 $76",
                "text": "小麥減量，讓不喜歡小麥味道的朋友，也能夠輕易地接受，但卻能獲得同樣的營養價值。  ★小麥精選研磨，香氣迷人  ★餅乾軟硬",
                "actions": [
                  {
                    "type": "uri",
                    "label": "前往購買",
                    "uri": "http://24h.pchome.com.tw/prod/DBAEA1-A9008AN2D?q=/S/DBAEA0"
                  }
                ]
              }
            ]
          }
        }
        
## D-0 [/d0]

### D-0 [GET]

+ Response 200 (application/json)

        {
          "type": "imagemap",
          "baseUrl": "https://i.imgur.com/X2Ely9e.jpg",
          "altText": "This is an imagemap",
          "baseSize": {
            "width": 1040,
            "height": 1040
          },
          "actions": [
            {
              "type": "message",
              "area": {
                "x": 0,
                "y": 0,
                "width": 340,
                "height": 1040
              },
              "text": "吃貨最愛"
            },
            {
              "type": "message",
              "area": {
                "x": 693,
                "y": 0,
                "width": 347,
                "height": 1040
              },
              "text": "生活小物"
            },
            {
              "type": "message",
              "area": {
                "x": 340,
                "y": 0,
                "width": 353,
                "height": 1040
              },
              "text": "流行配件"
            }
          ]
        }
        
## D-1 [/d1]

### D-1 [GET]

+ Response 200 (application/json)

                {
          "type": "template",
          "altText": "this is a carousel template",
          "template": {
            "type": "carousel",
            "actions": [],
            "columns": [
              {
                "thumbnailImageUrl": "http://a.ecimg.tw/items/DBAR4VA9007QKQE/000001_1523329760.jpg",
                "title": "【櫻桃爺爺】棗到幸福禮盒(經典牛軋糖+英式太妃糖+南棗核桃糕) 網路價 $359",
                "text": "．獨家款禮盒  櫻桃爺爺堅持純天然食材  ．甜度適中，不添加人工香料、防腐劑。 ",
                "actions": [
                  {
                    "type": "message",
                    "label": "前往購買",
                    "text": "http://24h.pchome.com.tw/prod/DBAR4V-A9007QKQE?q=/S/DBARA9"
                  }
                ]
              },
              {
                "thumbnailImageUrl": "https://a.ecimg.tw/items/DBAR5IA9008P1KO/000001_1516961585.jpg",
                "title": "【Kenji健司】醇。北海道牛奶法蘭酥(63g/6包入) 網路價 $69",
                "text": "★美式賣場知名品牌【Kenji健司】出品，優質、美味、安心  ★業界首創添加北海道牛奶7.3%，真材實料 ",
                "actions": [
                  {
                    "type": "uri",
                    "label": "前往購買",
                    "uri": "https://24h.pchome.com.tw/prod/DBAR5I-A9008P1KO"
                  }
                ]
              },
              {
                "thumbnailImageUrl": "http://a.ecimg.tw/items/DBAR5JA9006040P/000001_1487123117.jpg",
                "title": "[喬安牧場] 高梁 酒辣味牛肉乾 180g 網路價 $209",
                "text": "★新鮮100%-嚴選新鮮材料製作  ★衛生100%- 生產嚴格把關  ★創新100%- 口味，營養不斷研發 ",
                "actions": [
                  {
                    "type": "uri",
                    "label": "前往購買",
                    "uri": "http://24h.pchome.com.tw/prod/DBAR5J-A9006040P?q=/S/DBARAD"
                  }
                ]
              }
            ]
          }
        }